app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => ['web']], function (){

//Used to test eamils working
// Route::get('api/v1/mailTest', 'StoreController@mailTest');

Route::get('api/v1/search', 'SearchController@searchItems');
Route::get('api/v1/getMore', 'ItemController@getMoreItems');
Route::post('api/v1/issues/new', 'IssueController@create');

//Routes for Auth

Route::auth();

Route::get('', 'HomeController@index');
Route::get('ref/{aff}', 'HomeController@ref');
Route::get('home', 'HomeController@index');
Route::get('about', 'AboutController@aboutPage');
Route::get('redirect/{provider}', 'SocialAuthController@redirect');
Route::get('callback/{provider}', 'SocialAuthController@callback');
Route::get('mypocket', 'PocketController@index');

Route::get('privacy-policy', function(){
	return view('privacy-policy');
});

Route::get('search', 'SearchController@search');
Route::get('support', 'SupportController@index');
Route::group(['middleware' => 'auth'], function() {

	Route::get('logout', 'Auth\LoginController@logout');
	//User Routes
	Route::get('my-profile', 'UserController@profile')->name('my-profile');
	Route::patch('my-profile', 'UserController@update');

	//Boosted Items Routes
	Route::get('store/boosted-items', 'BoostedItemController@getBoostedItems');
	Route::get('store/boost-an-item', 'BoostedItemController@create');
	Route::put('api/v1/item/boost', 'BoostedItemController@store');

	//Store Routes
	Route::get('store/sellers', 'StoreController@sellers');
	Route::get('api/v1/seller/remove/{id}', 'StoreController@removeSeller');
	Route::get('api/v1/seller/invite/{email}', 'StoreController@inviteSeller');
	Route::get('store/items', 'ItemController@storeItems');
	Route::get('store/add-item', 'ItemController@create');
	Route::get('store/payment', 'StoreController@changePayment');
	Route::patch('store/payment/{store}', 'StoreController@updatePayment');
	Route::get('store/plan', 'StoreController@changePlan');
	Route::patch('store/plan/{store}', 'StoreController@updatePlan');
	Route::resource('store', 'StoreController');
	Route::put('store', 'StoreController@store');
	Route::resource('item', 'ItemController');
	//Route::get('store/conversations', 'ConversationController@getStoreConverstaions');



	//Images Routes
	Route::post('store/image/upload', 'ImageController@upload');
	Route::post('api/v1/image/upload/profile', 'ImageController@uploadProfile');
	Route::post('api/v1/image/upload/store', 'ImageController@uploadStore');
	Route::post('api/v1/image/upload/cover', 'ImageController@uploadCover');
	Route::get('api/v1/image/getItemImages/{id}','ImageController@getItemImages');
	Route::get('api/v1/image/remove/{id}', 'ImageController@remove');

	//Message Routes
	Route::post('api/v1/messages/new', 'MessageController@newMessage');
	Route::get('conversations', 'ConversationController@index');
	Route::get('api/v1/conversations/getUsersConversations', 'ConversationController@getUsersConversations');
	Route::get('api/v1/conversations/getStoreConversations', 'ConversationController@getStoreConversations');
	Route::get('api/v1/conversations/leaveConversation/{id}', 'ConversationController@leaveConversation');
	Route::get('api/v1/conversations/getUnreadCount', 'ConversationController@getUnreadCount');
	Route::get('conversation/{id}', 'ConversationController@getConversation');
	Route::get('api/v1/getMessages', 'ConversationController@getMessages');
	Route::post('api/v1/messages/sendMessage', 'MessageController@sendMessage');
	//Route::get('conversations', 'ConversationController@')

	//My Pocket Routes
	Route::get('api/v1/mypocket/getPocket', 'PocketController@getPocket');
	Route::get('api/v1/mypocket/removeFromPocket/{type}/{id}', 'PocketController@removeFromPocket');
	Route::get('api/v1/mypocket/addToPocket/{type}/{id}', 'PocketController@addToPocket');
});
//Route::post('api/searchStores', 'SearchController@searchStores');

Route::get('marketplace/{id}/{store}', 'StoreController@showStore');
Route::get('item/{store}/{id}/{item}', 'ItemController@getItem');

});

// Route::get('mobilelistings', function () {
//     return view('mobilelistings');
// });

// Route::get('store', function () {
//     return view('store');
// });

app/Store.php
<?php

namespace pocketbarn;

use Illuminate\Database\Eloquent\Model;
use Laravel\Cashier\Billable;
class Store extends Model
{
	use Billable;

	// public function plans()
	// {
	// 	return $this->hasMany(Subscription::class)->orderby('created_at', 'desc');
	// }
    public function items()
    {
    	return $this->hasMany('pocketbarn\Item');
    }

    public function boostedItems()
    {
        return $this->hasManyThrough('pocketbarn\Item', 'pocketbarn\BoostedItem');
    }

    public function users()
    {
    	return $this->hasMany('pocketbarn\User');
    }

    public static function getPlan($store)
    {
        $plans = Plan::all();
        foreach($plans as $plan)
        {
            if($store->subscribedToPlan($plan->stripe_id, 'main') || $store->subscribedToPlan($plan->stripe_id.'_year', 'main'))
            {
                return $plan;
            }
        }
    }

    public static function limitReached($store)
    {
        //Check of unlimited plan
          if($store->getPlan($store)->stripe_id == 'est' || $store->getPlan($store)->stripe_id == 'est_year' ) return false;

          if($store->items->count() == $store->getPlan($store)->item_limit)
          {
            return true;
          }
          else{
            return false;
          }
    }
}

app/Http/Controllers/StoreController.php
<?php

namespace pocketbarn\Http\Controllers;

use Illuminate\Http\Request;
use pocketbarn\Mail\WelcomeStore;
use pocketbarn\Mail\NewSeller;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use pocketbarn\Store;
use pocketbarn\User;
use pocketbarn\Plan;
use pocketbarn\Affiliate;
use JavaScript;
use Image;

class StoreController extends Controller
{



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Get Current User
        $user = auth()->user();
        //Get Store info
        $store = $user->store;
        if(!$store)
        {
            return redirect('/store/create');
        }
        //Get all Store owners
        $store->users;
        if($store->profile_img){
            $store->profile_img = Storage::url('stores/'.$store->id.'/'.$store->profile_img);
        }
        if($store->cover_img){
            $store->cover_img = Storage::url('stores/'.$store->id.'/'.$store->cover_img);
        }

        return view('store.edit')->with(['user' => $user, 'store' => $store, 'states' => $this->states]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = auth()->user();
        if($user->store_id)
        {
            return redirect('/store');
        }
        $plans = Plan::orderBy('monthly', 'asc')->get();
        $plans = $plans->reject(function ($plan) {
                return $plan->stripe_id == 'free';
            });
        //Add store_id as a javascript variable to use in Vue
        JavaScript::put([
            'store' => $user->store_id,
            'stripeKey' => env('STRIPE_KEY')
        ]);
        return view('store.create')->with(['user'=> $user, 'states' => $this->states, 'plans' => $plans, 'years' => $this->years, 'months' => $this->months]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = auth()->user();
        //array_push($request, $request->file('avatar'));

        $this->validate($request, [
            'store_name' => 'required|unique:stores,name',
            'address_line1' => 'required',
            'address_city' => 'required',
            'address_state' => 'required',
            'address_zip' => 'required',
            'plan' => 'required',
            'stripeToken' => 'required_unless:plan,free_new'
        ]);

        $cordinates = $this->get_lat_lng($request->input('address_zip'));

        $store = new Store;

        $store->name = $request->input('store_name');
        $store->slug = $this->make_slug($request->input('store_name'));
        $store->street = $request->input('address_line1');
        $store->city = $request->input('address_city');
        $store->state = $request->input('address_state');
        $store->zip = $request->input('address_zip');
        $store->lat = $cordinates['lat'];
        $store->lng = $cordinates['lng'];
        $store->owned_by = $user->id;

        $store->save();
        $plan =  $request->input('plan');
        $plan_type = $request->input('plan_type');
        $stripeToken = $request->input('stripeToken');
        if($plan_type == 'yearly'){
            $plan = $plan.'_year';
        }
        $store->newSubscription('main', $plan)->create($stripeToken);

        session()->flash('status', 'Your Marketplace has been created');
        session()->flash('status_type', 'type=success');

        //Send welcome email to user
        Mail::to($user->email)->queue(new WelcomeStore($store));

        $mailchimp = app('Mailchimp');
        try {
            $mailchimp
                ->lists
                ->subscribe(
                    env('MAILCHIMP_MARKETPLACE_LIST_ID'),
                    ['email' => $user->email],
                    ['FNAME' => $user->name],
                  null,
                  false
                );
                } catch (\Mailchimp_List_AlreadySubscribed $e) {
                   
                } catch (\Mailchimp_Error $e) {
                    
                }

        //Set User as sotre owner
        $user->store_id = $store->id;
        $user->save();

        //Give credit to the Affiliate is exsits
        if($request->cookie('pb_aff'))
        {
            $aff = Affiliate::where('key', '=', $request->cookie('pb_aff'))->firstOrFail();
            //dd($aff);
            $aff->stores()->attach($store->id, ['plan' => $plan]);
            $aff->save;
        }

        return redirect('/store');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = auth()->user();

         $this->validate($request, [
            'store_name' => 'required|unique:stores,name,'.$id,
            'street' => 'required',
            'city' => 'required',
            'state' => 'required',
            'zip' => 'required',
            'phone' => 'string',
            'story' => 'string',
            'policies' => 'string',
            'website' => 'url',
            'show_address' => 'boolean',
            'profile_img' => 'image|dimensions:min_width=200,min_height=200|mimes:jpg,jpeg,png,gif',
            'cover_img' => 'image|dimensions:min_width=960,min_height=400|mimes:jpg,jpeg,png',

        ]);

          $store = Store::find($id);

         if($request->file('cover_img'))
        {
            $cover_img = $request->file('cover_img');
            //Hash name and compile with origianl extention
            $cover_ext = $cover_img->getClientOriginalExtension();
            $cover_storage_name = md5($cover_img->getClientOriginalName().time());
            $coverPath = $cover_storage_name.'.'.$cover_ext;

            //Make and resize the Image
            $cover_img = Image::make($cover_img)->orientate()->fit(1920, 800, function ($constraint) {
                $constraint->upsize();
            }, 'top');

            //Convert to stream
            $cover_img = $cover_img->stream();
            //Save to S3
            Storage::put('stores/'.$store->id.'/'.$coverPath, $cover_img->__toString());
            //Save the file name for database
            $store->cover_img = $coverPath;
        }
        if($request->file('profile_img'))
        {
            $profile_img = $request->file('profile_img');
            //Hash name and compile with origianl extention
            $profile_ext = $profile_img->getClientOriginalExtension();
            $profile_storage_name = md5($profile_img->getClientOriginalName().time());
            $profilePath = $profile_storage_name.'.'.$profile_ext;

            //Make and resize the Image
            $profile_img = Image::make($profile_img)->orientate()->fit(200, 200, function ($constraint) {
                $constraint->upsize();
            });

            //Convert to stream
            $profile_img = $profile_img->stream();
            //Save to S3
            Storage::put('stores/'.$store->id.'/'.$profilePath, $profile_img->__toString());
            //Save the file name for database
            $store->profile_img = $profilePath;
        }

        $cordinates = get_lat_lng($request->input('zip'));



        $store->name = $request->input('store_name');
        $store->street = $request->input('street');
        $store->city = $request->input('city');
        $store->state = $request->input('state');
        $store->zip = $request->input('zip');
        $store->lat = $cordinates['lat'];
        $store->lng = $cordinates['lng'];
        $store->phone = $request->input('phone');
        $store->show_address = $request->input('show_address');
        $store->website = $request->input('website');
        $store->story = $this->make_paragraphs($request->input('story'));
        $store->policies = $this->make_paragraphs($request->input('policies'));


        $store->save();

        session()->flash('status', 'Your Marketplace has been created');
        session()->flash('status_type', 'type=success');

        return redirect('store')->with(['user' => $user, 'store' => $store, 'states' => $this->states]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //Find Store
        $store = Store::find($id);

        //Cancel Subscription
        $store->subscription('main')->cancelNow();
        foreach($store->users as $user) {
            $user->store_id = 0;
            $user->save();
        }

        $store->delete();

        return response('success', 200);
    }


    public function sellers()
    {
        //Get sotre info and all sellers associated
        $store = Store::find(auth()->user()->store_id);
        $store->users;
        foreach($store->users as $user)
        {
            if($user->avatar)
            {
                $user->avatar = Storage::url('users/'.$user->id.'/'.$user->avatar);
            }
        }

        //Add store_id as a javascript variable to use in Vue
        JavaScript::put([
            'store' => $store->id,
            'itemName' => ''
        ]);

        //Return view of sellers
        return view('store.sellers')->with('store', $store);
    }

resources/views/store/changePayment.blade.php
@extends('layouts.mainlayout')

@section('title', 'Update Payment Type')

@section('content')
<section class="container account-page" id="pb-app-store" v-cloak>
	@include('store.sidebar')
		@if (count($errors) > 0)
		   <alert type=error>
		        <ul>
		            @foreach ($errors->all() as $error)
		                <li>{{ $error }}</li>
		            @endforeach
		        </ul>
		    </alert>
		@endif
		<div class="Store Form">
			<h3>Change your Payment</h3>
			<div class="CreditCard">
			<h4>Current Payment </h4>
			<p class="cc_num">XXXX XXXX XXXX {{$store->card_last_four}}</p>
			<p class="cc_type">{{$store->card_brand}}</p>
			</div>
			<form method="POST" action="/store/payment/{{$store->id}}" class="Plans--Form" id="marketplace-form" enctype="multipart/form-data">
				{{ method_field('PATCH') }}
				{{ csrf_field() }}
				<h3>New Payment Info</h3>
				<p class="payment-errors error animated"></p>
				<div class="Form--input-group">
					<label>Credit card number</label>
					<input class="Form--input masked" type="tel" id="ccn" name="ccn" placeholder="XXXX XXXX XXXX XXXX" data-stripe="number" value="{{ old('ccn') }}">
					<span class="Form__error">{{ $errors->first('ccn') }}</span>
				</div>
				<div class="Form--input-group exp">
					{{-- <label>Expriation date</label> --}}
					<select class="Form--input exp-month" type="text" name="exp-month" data-stripe="exp-month">
						@foreach($months as $month => $month_ab)
							<option {!! (old('exp-month') == $month_ab ? 'selected'  : '' ) !!} value="{{ $month }}">{{ $month_ab }}</option>
						@endforeach
					</select>
					<select class="Form--input exp-year" type="text" name="exp-year" data-stripe="exp-year">
						@foreach($years as $year)
							<option {!! (old('exp-year') == $year ? 'selected'  : '' ) !!} value="{{ $year }}">{{ $year }}</option>
						@endforeach
					</select>
					<span class="Form__error">{{ $errors->first('exp-year') }}</span>
				</div>
				<div class="Form--input-group">
					<label>CVC</label>
					<input class="Form--input" type="text" name="cvc" placeholder="123" data-stripe="cvc" value="{{ old('cvc') }}">
					<span class="Form__error">{{ $errors->first('cvc') }}</span>
				</div>
				<div class="Form--input-group">
					<button class="btn" type="submit">Update Payment</button>
				</div>
			</form>

		</div>

</section>


@endsection

@section ('footer')
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script>
Stripe.setPublishableKey(window.stripeKey);
    jQuery(function($) {
        $('#marketplace-form').submit(function(event) {
        	event.preventDefault();
            var $form = $(this);
            $form.find('button').prop('disabled', true);
            Stripe.card.createToken($form, stripeResponseHandler);

            return false;
        });
    });

    var stripeResponseHandler = function(status, response) {
        var $form = $('#marketplace-form');

        if (response.error) {
            $form.find('.payment-errors').text(response.error.message).addClass('flash');
            $form.find('button').prop('disabled', false);
        } else {
            var token = response.id;
            $form.append($('<input type="hidden" name="stripeToken" />').val(token));
            $form.get(0).submit();
        }
    };
   </script>
@endsection

resources/views/store/conversations.blade.php
@extends('layouts.mainlayout')

@section('title', 'My Marketplace Conversations ')

@section('content')
<section class="container account-page" id="pb-app-conversations">
 @if(session()->has('status'))
        <alert {{ session('status_type') }}>{{ session('status') }}</alert>
    @endif
	@include('store.sidebar')
	<div class="Store">
	<a href="/conversations"><i class="pe-7s-angle-left"></i> Back to Conversations</a>
			<conversations :user="{{ $user }}" :store="{{ $user->store_id }}"></messages>

	</div>
</section>

@endsection

@section ('footer')
<script>
	// Accordian
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
    acc[i].onclick = function(){
        this.classList.toggle("active");
        this.nextElementSibling.classList.toggle("show");
    }
}
</script>
@endsection

resources/views/store/create.blade.php
@extends('layouts.mainlayout')

@section('title', 'Create Marketplace')
@section('meta_desc', 'Create your marketplace on pocketbarn')
@section('content')
<section class="container account-page" id="pb-app" v-cloak>
	@include('user.sidebar')
		<div class="Store Form">
			<h1>Create my Marketplace</h1>
			<form method="POST" action="{{route('store.store')}}" class="" id="marketplace-form">
				{{ method_field('PUT') }}
				{{ csrf_field() }}
				<div class="Form--input-group">
					*<input class="Form--input" type="text" name="store_name" placeholder="Marketplace Name" value="{{ old('store_name') }}">
					<span class="Form__error">{{ $errors->first('store_name') }}</span>
				</div>
				<div class="Form--input-group">
					*<input class="Form--input" type="text" name="address_line1" placeholder="Steet Address" value="{{ old('address_line1') }}">
					<span class="Form__error">{{ $errors->first('address_line1') }}</span>
				</div>
				<div class="Form--input-group">
					*<input class="Form--input" type="text" name="address_city" placeholder="City" value="{{ old('address_city') }}">
					<span class="Form__error">{{ $errors->first('address_city') }}</span>
				</div>
				<div class="Form--input-group">
					*<select class="Form--input" type="text" name="address_state">
						@foreach($states as $ab => $name)
							<option {!! (old('address_state') == $ab ? 'selected' : '' ) !!} value="{{ $ab }}">{{ $name }}</option>
						@endforeach
					</select>
					<span class="Form__error">{{ $errors->first('address_state') }}</span>
				</div>
				<div class="Form--input-group">
					*<input class="Form--input" type="text" name="address_zip" placeholder="Zipcode" value="{{ old('address_zip') }}">
					<span class="Form__error">{{ $errors->first('address_zip') }}</span>
				</div>
				<h3>Choose Your Plan</h3>
				<div class="Plans">
					@foreach($plans as $plan)

						<div class="Plan">
							<div class="Plan--top">
								<h5 class="Plan--name">{{ $plan->name }}</h5>
								<p class="Plan--price">@if($plan->monthly) ${{ $plan->monthly}}/mo  @else FREE @endif</p>
							</div>
							<div class="Plan--Description">
							<ul>
								{!! $plan->description !!}
							</ul>
							</div>
							<div class="Plan__choose">
								<div class="Plan--option">
									<input type="radio" name="plan" v-model="plan" value="{{$plan->stripe_id}}" {!! (old('plan') == $plan->stripe_id ? 'checked' : '' ) !!} >
									<label>@if($plan->monthly) ${{ $plan->monthly}}/mo @else FREE @endif</label>
								</div>
								<div class="Plan--option">
									@if($plan->stripe_id != 'free_new' )
										<input type="radio" name="plan" v-model="plan" value="{{$plan->stripe_id}}_year" {!! (old('plan') == $plan->stripe_id ? 'checked' : '' ) !!} >
										<label>${{ $plan->yearly}}/yr (Save ${!! round(($plan->monthly*12) - $plan->yearly) !!})</label>
									@endif
								</div>

							</div>
						</div>


					@endforeach
				</div>
				<div class="Form--input-group Plan--type"  v-if="plan != 'free_new'" >
					<h5>How would you like to pay?</h5>
					@foreach($plans as $plan)
						@if($plan->stripe_id != 'free_new')
							<div v-if="plan === '{{$plan->stripe_id}}' || plan === '{{$plan->stripe_id}}_year'" >
								<div class="Form--radio-group">
									<input class="Form--radio" type="radio" name="plan_type"  {!! (old('plan_type') == true ? 'checked' : '' ) !!} value="monthly">
									<label>Monthly ${{$plan->monthly}}</label>
								</div>
								<div class="Form--radio-group">
									<input class="Form--radio" type="radio"  name="plan_type" {!! (old('plan_type') == true ? 'checked' : '' ) !!} value="yearly">
									<label>Yearly ${{$plan->yearly}} (Save ${!! round(($plan->monthly*12) - $plan->yearly) !!})</label>
								</div>
							<span class="Form__error">{{ $errors->first('show_address') }}</span>
							</div>
						@endif
					@endforeach
				</div>
				<div v-if="plan != 'free_new'">
					<h3>Payment Info</h3>
					<p class="payment-errors error animated"></p>
					<div class="Form--input-group">
						<label>Credit card number</label>
						<input class="Form--input masked" type="tel" id="ccn" name="ccn" placeholder="XXXX XXXX XXXX XXXX" data-stripe="number" value="{{ old('ccn') }}">
						<span class="Form__error">{{ $errors->first('ccn') }}</span>
					</div>
					<div class="Form--input-group exp">
						{{-- <label>Expriation date</label> --}}
						<select class="Form--input exp-month" type="text" name="exp-month" data-stripe="exp-month">
							@foreach($months as $month => $month_ab)
								<option {!! (old('exp-month') == $month_ab ? 'selected'  : '' ) !!} value="{{ $month }}">{{ $month_ab }}</option>
							@endforeach
						</select>
						<select class="Form--input exp-year" type="text" name="exp-year" data-stripe="exp-year">
							@foreach($years as $year)
								<option {!! (old('exp-year') == $year ? 'selected'  : '' ) !!} value="{{ $year }}">{{ $year }}</option>
							@endforeach
						</select>
						<span class="Form__error">{{ $errors->first('exp-year') }}</span>
					</div>
					<div class="Form--input-group">
						<label>CVC</label>
						<input class="Form--input" type="text" name="cvc" placeholder="123" data-stripe="cvc" value="{{ old('cvc') }}">
						<span class="Form__error">{{ $errors->first('cvc') }}</span>
					</div>
				</div>
				<div class="Form--input-group">
					<button class="btn" @click.prevent="createStore()" type="submit">Create Marketplace</button>
				</div>
				<small>* required information</small>
			</form>
			<div class="Form--hints">
			</div>
		</div>

</section>


@endsection

@section ('footer')
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
@endsection

resources/views/store/items.blade.php
@extends('layouts.mainlayout')

@section('title', 'Marketplace Items')

@section('content')
<section class="container account-page" id="pb-app-store">
	@include('store.sidebar')
	@if($store->subscribedToPlan('est', 'main') || $store->subscribedToPlan('est_year', 'main'))
		@if($items->count() > 0 )
			<a href="/store/add-item" class="btn"><i class="pb-icon plus ico-small"></i> New Item</a>
		@endif
	@endif
		@if (count($errors) > 0)
		   <alert type=error>
		        <ul>
		            @foreach ($errors->all() as $error)
		                <li>{{ $error }}</li>
		            @endforeach
		        </ul>
		    </alert>
		@endif
		<div class="Store Items">
		<h3>{{ $store->name }} Items</h3>
			{{-- @if(count($items) > 0) --}}
			<div class="Cards">
				@foreach($items as $item)

					<div class="Card storeCard animated fadeInUpBig"  transition="slideUp">
						@if($item->status == 'active')
			      			<p class="Card--status active"><i class="pb-icon check ico-small"></i> Active</p>
			      		@elseif($item->status == 'in-active')
			      			<p class="Card--status in-active"><i class="pb-icon diskette ico-small"></i> Saved</p>
			      		@endif
						
					    	<div class="Card--image">
					    		<a href="/item/{{$item->id}}" class="Card--link" >
						    		@if($item->featured_image)
						      			<img src="{{$item->featured_image}}">
						      		@else
						      			<img src="/assets/images/no-featured.jpg">
						      		@endif
					      		</a>
					      	</div>
					      </a>

					    	<div class="Card--action">
					      		<a href="/item/{{$store->slug}}/{{$item->id}}/{{$item->slug}}" class="Card--link" >
					      			<span class="Card--title">{{$item->title}}</span>
					      		</a>
					      		<a href="#" class="Card--location"><i class="pb-icon map-marker ico-small"></i>{{ $store->city }}, {{ $store->state }}</a>
					    	</div>
					  	</div>

					 @endforeach
					 @for ($i = 0; $i < $blanks; $i++)
					 	<div class="Card storeCard animated fadeInUpBig"  transition="slideUp">
						
					    	<div class="Card--image">
					    		<a href="/store/add-item" class="Card--link" >
					      			<img src="/assets/images/new-item.jpg">
					      		</a>
					      	</div>
					     

					    	<div class="Card--action">
					      		<a href="/store/add-item" class="Card--link" >
					      			<span class="Card--title">Add New Item</span>
					      		</a>
					      		<a href="#" class="Card--location"><i class="pb-icon map-marker ico-small"></i>{{ $store->city }}, {{ $store->state }}</a>
					    	</div>
					  	</div>
					 @endfor
			</div>
			@if($limitReached)
			<div class="Items--limit-reached">
				<p><i class="pe-7s-attention"></i></p>
				<div class="item-alert">
					<h4>You have reached your item Limit.</h4>
					<h5>To add more items, please <a href="/store/plan">upgrade your account</a></h5>
				</div>
			</div>
			@endif
			{{-- For Unlimted Plans --}}
			@if($store->subscribedToPlan('est', 'main') || $store->subscribedToPlan('est_year', 'main'))
				@if($items->count() <= 0 )
				<div class="item-alert">
					<h4>You do not have any items yet. <a href="/store/add-item">Add some now!</a></h4>
				</div>
				@endif
				<a href="/store/add-item" class="btn"><i class="pb-ico check ico-small"></i> New Item</a>
			@endif
		</div>

</section>


@endsection

@section ('footer')
@endsection